CREATE DATABASE "DWPCTenant"

  ON (NAME = "DWPCTenant",

  FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DWPCTenant.mdf', SIZE = 2000MB)

  LOG ON (NAME = "DWPCTenant_log",

  FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DWPCTenant_log.ldf', SIZE = 1000MB);

  

ALTER DATABASE DWPCTenant

  SET ALLOW_SNAPSHOT_ISOLATION ON;



ALTER DATABASE DWPCTenant

  SET READ_COMMITTED_SNAPSHOT ON;